import Main from './components/Main'
import Navbar from './components/Navbar'
export const metadata = {
  title: 'Paktube || Home',
  description: 'Generated by MHasaan Mumtaz',
}
export default async function Home() {
  const url = "https://newsapi.org/v2/everything?q=apple&from=2023-06-06&to=2023-06-06&sortBy=popularity&apiKey=060b4b10339f4b739d6f5ebd613519a2&page=1&pageSize=4"
  const res = await fetch(url)
  const apiData = await res.json();
  const newsData = apiData.articles;
  return (
    <div>
      <Navbar />
      <Main data={newsData} />
    </div>
  )
}
